//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedBack_id { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> approve { get; set; }
        public string userId { get; set; }
        public string img { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
