//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggestion1
    {
        public int id { get; set; }
        public string username { get; set; }
        public string moviename { get; set; }
        public string movie_history { get; set; }
        public string movie_type { get; set; }
        public string siggestion { get; set; }
    }
}
